version: "3.8"

services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env              
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    env_file:
      - .env              
    environment:
      DB_HOST: db         
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["/app/entrypoint.sh"]

volumes:
  db_data:
