name: Fyyur CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/fyyur
  DOCKER_TAG: latest
  FLASK_APP: app.py
  FLASK_ENV: development
  SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

jobs:
  setup:
    name: Setup Python Environment
    runs-on: ubuntu-latest
    outputs:
      python-path: ${{ steps.python-path.outputs.python-location }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        id: python-path
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.18'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  snyk_scan:
    name: Snyk Dependency Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
  
      - name: Install Snyk CLI
        run: npm install -g snyk
  
      - name: Run Snyk Test and Monitor
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test && snyk monitor


  sonar_scan:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run SonarQube scanner
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: fyyur
          organization: neirezcher
          token: ${{ secrets.SONAR_TOKEN }}

  docker_build_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: [setup, snyk_scan, sonar_scan]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $DOCKER_IMAGE_NAME:$DOCKER_TAG .

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE_NAME:$DOCKER_TAG
